import type {
  ResolvedWebsiteTheme,
  ThemeDesignTokens,
  WebsiteTheme,
  WebsiteThemeSelection,
} from "../src/types";
import { themeAccessibilityAudit } from "../src/components/themeAdapter";

export const themeTokens: ThemeDesignTokens = {
  colors: {
    primary: "#1F2937",
    primary_foreground: "#FFFFFF",
    secondary: "#374151",
    secondary_foreground: "#FFFFFF",
    accent: "#0F766E",
    accent_foreground: "#FFFFFF",
    neutral: "#4B5563",
    neutral_foreground: "#FFFFFF",
    background: "#FFFFFF",
    surface: "#F3F4F6",
    text: "#111827",
    heading: "#0F172A",
    success: "#166534",
    success_foreground: "#FFFFFF",
    warning: "#92400E",
    warning_foreground: "#FFFFFF",
    error: "#B91C1C",
    error_foreground: "#FFFFFF",
    focus: "#005FCC",
  },
  typography: {
    heading_family: "system-ui, sans-serif",
    body_family: "system-ui, sans-serif",
    heading_weight: 700,
    body_weight: 400,
    font_scale: {
      xs: 0.75,
      sm: 0.875,
      base: 1,
      lg: 1.125,
      xl: 1.25,
      xxl: 1.5,
      display: 2.25,
    },
    line_height: { heading: 1.2, body: 1.6 },
    letter_spacing: { heading: -0.02, body: 0 },
  },
  spacing: {
    scale: { zero: 0, xs: 0.25, sm: 0.5, md: 1, lg: 1.5, xl: 2, xxl: 3 },
    section_spacing: { mobile: 3, tablet: 4, desktop: 5 },
  },
  content_widths: { narrow: 720, content: 1120, wide: 1440 },
  borders: {
    widths: { thin: 1, medium: 2, thick: 3 },
    radii: { small: 4, medium: 8, large: 16, pill: 9999 },
  },
  shadows: {
    none: "none",
    low: "0 1px 2px rgba(15, 23, 42, 0.12)",
    medium: "0 4px 12px rgba(15, 23, 42, 0.16)",
    high: "0 12px 28px rgba(15, 23, 42, 0.20)",
  },
  buttons: {
    background: "primary",
    text: "primary_foreground",
    border: "primary_foreground",
    hover_background: "secondary",
    focus: "primary_foreground",
    border_width: "medium",
    border_radius: "medium",
    padding_inline: "lg",
    padding_block: "sm",
    min_height: 44,
    font_weight: 700,
  },
  cards: {
    background: "surface",
    text: "text",
    border: "neutral",
    border_width: "thin",
    border_radius: "large",
    shadow: "low",
    padding: "lg",
  },
  navigation: {
    background: "primary",
    text: "primary_foreground",
    hover: "primary_foreground",
    active: "primary_foreground",
    focus: "primary_foreground",
    item_spacing: "md",
    min_target_size: 44,
  },
  cta: {
    background: "surface",
    text: "heading",
    button_background: "primary",
    button_text: "primary_foreground",
    focus: "focus",
    border_radius: "large",
    section_spacing: "xl",
    min_target_size: 44,
  },
  responsive: {
    mobile_max: 767,
    tablet_min: 768,
    tablet_max: 1023,
    desktop_min: 1024,
  },
  layout: {
    max_content_columns: 3,
    content_alignment: "left",
    mobile_stack: true,
    gutter: "lg",
    overflow_behavior: "wrap",
  },
  motion: {
    duration_fast_ms: 120,
    duration_normal_ms: 200,
    duration_slow_ms: 320,
    easing: "ease-out",
    reduced_motion: "disable_nonessential",
  },
};

const accessibility = themeAccessibilityAudit(themeTokens);

export function fallbackTheme(websiteId = 31): ResolvedWebsiteTheme {
  return {
    website_id: websiteId,
    theme: null,
    selection: null,
    effective_tokens: structuredClone(themeTokens),
    accessibility: {
      valid: !accessibility.failures.length,
      ratios: structuredClone(accessibility.ratios),
      failures: [...accessibility.failures],
    },
    fallback_used: true,
    fallback_reason: "No approved Theme is selected; Atlas neutral presentation is active.",
    source_identity: {
      mode: "neutral_fallback",
      website_id: websiteId,
      theme_id: null,
      theme_key: "atlas-neutral",
      theme_version: 1,
      token_contract_version: 1,
      token_hash_sha256: "a".repeat(64),
      selection_id: null,
      selection_version: null,
    },
  };
}

export function selectedTheme(websiteId = 31): ResolvedWebsiteTheme {
  const theme: WebsiteTheme = {
    id: 71,
    website_id: websiteId,
    business_id: 11,
    brand_id: 21,
    theme_key: "governed-theme",
    theme_name: "Governed Theme",
    version: 2,
    token_contract_version: 1,
    design_tokens: structuredClone(themeTokens),
    token_hash_sha256: "b".repeat(64),
    description: "A Website-owned Theme.",
    lifecycle_status: "available",
    approval_status: "approved",
    created_by: "Operator",
    provenance_type: "operator_configured",
    provenance_notes: "Configured from approved presentation decisions.",
    approved_by: "Approver",
    approved_at: "2026-08-04T20:00:00Z",
    created_at: "2026-08-04T19:00:00Z",
    updated_at: "2026-08-04T20:00:00Z",
  };
  const selection: WebsiteThemeSelection = {
    id: 81,
    website_id: websiteId,
    theme_id: theme.id,
    version: 3,
    status: "active",
    selected_by: "Operator",
    rationale: "Approved Website presentation.",
    selected_at: "2026-08-04T20:01:00Z",
    created_at: "2026-08-04T20:01:00Z",
    updated_at: "2026-08-04T20:01:00Z",
  };
  return {
    website_id: websiteId,
    theme,
    selection,
    effective_tokens: structuredClone(themeTokens),
    accessibility: {
      valid: !accessibility.failures.length,
      ratios: structuredClone(accessibility.ratios),
      failures: [...accessibility.failures],
    },
    fallback_used: false,
    fallback_reason: null,
    source_identity: {
      mode: "selected",
      website_id: websiteId,
      theme_id: theme.id,
      theme_key: theme.theme_key,
      theme_version: theme.version,
      token_contract_version: theme.token_contract_version,
      token_hash_sha256: theme.token_hash_sha256,
      selection_id: selection.id,
      selection_version: selection.version,
    },
  };
}
