import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, FileCode2, LockKeyhole, RefreshCw } from "lucide-react";
import { apiRequest } from "../api";
import type { WordPressMetadataApplyResult, WordPressMetadataDryRun, WordPressMetadataGate, WordPressMetadataRollbackDryRun, WordPressMetadataVerification } from "../types";

const PAGE_ID = 41;

export default function WordPressMetadataSafetyPage() {
  const [dry, setDry] = useState<WordPressMetadataDryRun | null>(null);
  const [verify, setVerify] = useState<WordPressMetadataVerification | null>(null);
  const [rollback, setRollback] = useState<WordPressMetadataRollbackDryRun | null>(null);
  const [result, setResult] = useState<WordPressMetadataApplyResult | null>(null);
  const [phrase, setPhrase] = useState(""); const [dataBackup, setDataBackup] = useState("");
  const [mediaBackup, setMediaBackup] = useState(""); const [programBackup, setProgramBackup] = useState("");
  const [wpBackup, setWpBackup] = useState(""); const [wpBackupTime, setWpBackupTime] = useState("");
  const [databaseIncluded, setDatabaseIncluded] = useState(false); const [pluginsIncluded, setPluginsIncluded] = useState(false); const [restoreConfirmed, setRestoreConfirmed] = useState(false);
  const [rollbackPhrase, setRollbackPhrase] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const tokenFresh = Boolean(dry?.expires_at && Date.parse(dry.expires_at) > Date.now());
  const backupProof = () => ({ confirmed_data_backup_file: dataBackup.trim(), confirmed_media_backup_identity: mediaBackup.trim(), confirmed_program_backup_identity: programBackup.trim(), wordpress_backup_reference: wpBackup.trim(), wordpress_backup_timestamp: new Date(wpBackupTime).toISOString(), wordpress_backup_database_included: databaseIncluded, wordpress_backup_plugin_files_included: pluginsIncluded, wordpress_restore_capability_confirmed: restoreConfirmed });
  const backupsReady = Boolean(dataBackup.trim() && mediaBackup.trim() && programBackup.trim() && wpBackup.trim() && wpBackupTime && databaseIncluded && pluginsIncluded && restoreConfirmed);
  const canApply = useMemo(() => Boolean(dry?.ready && dry.confirmation_token && tokenFresh && phrase === dry.confirmation_phrase && backupsReady), [dry, tokenFresh, phrase, backupsReady]);

  async function run<T>(work: () => Promise<T>, save: (value: T) => void) { setBusy(true); setError(null); try { save(await work()); } catch (value) { setError(value instanceof Error ? value.message : "Request failed."); } finally { setBusy(false); } }
  function runDry() { if (!backupsReady) { setError("Enter and attest all backup identities before dry-run."); return; } setPhrase(""); setResult(null); void run(() => apiRequest<WordPressMetadataDryRun>(`/api/wordpress/metadata/dry-run/${PAGE_ID}`, { method: "POST", body: JSON.stringify(backupProof()) }), setDry); }
  function runVerify() { void run(() => apiRequest<WordPressMetadataVerification>(`/api/wordpress/metadata/verify/${PAGE_ID}`, { method: "POST" }), setVerify); }
  function runRollbackDry() { if (!backupsReady) return; setRollbackPhrase(""); void run(() => apiRequest<WordPressMetadataRollbackDryRun>(`/api/wordpress/metadata/rollback/dry-run/${PAGE_ID}`, { method: "POST", body: JSON.stringify(backupProof()) }), setRollback); }
  function apply() { if (!canApply || !dry?.confirmation_token) return; void run(() => apiRequest<WordPressMetadataApplyResult>(`/api/wordpress/metadata/apply/${PAGE_ID}`, { method: "POST", body: JSON.stringify({ confirmation_token: dry.confirmation_token, confirmation_phrase: phrase, ...backupProof() }) }), setResult); }
  const rollbackReady = Boolean(rollback?.ready && rollback.confirmation_token && rollbackPhrase === rollback.confirmation_phrase && backupsReady);
  function applyRollback() { if (!rollbackReady || !rollback?.confirmation_token) return; void run(() => apiRequest(`/api/wordpress/metadata/rollback/apply/${PAGE_ID}`, { method: "POST", body: JSON.stringify({ confirmation_token: rollback.confirmation_token, confirmation_phrase: rollbackPhrase, ...backupProof() }) }), () => runVerify()); }

  return <section className="page wordpressPublishSafetySandboxPage">
    <header className="pageHeader"><div><span className="eyebrow">Orlando only · page 41 · post 8</span><h1>WordPress Metadata Safety</h1><p>Guarded Project Atlas metadata bridge controls. Plugin installation and activation happen separately in WordPress and are not available here.</p></div></header>
    <div className="wordpressSafetyNotice"><LockKeyhole size={22}/><div><strong>Fixed metadata scope</strong><p>Media 31 only; media 32 excluded. No title, H1, body, excerpt, slug, canonical, status, featured-image, Site Title, Tagline, media, cache, or bulk controls.</p></div></div>
    <section className="panel"><h2>Backup-bound read-only inspection</h2><label>Atlas Data Backup JSON<input value={dataBackup} onChange={e => setDataBackup(e.target.value)}/></label><label>Atlas Media Backup identity<input value={mediaBackup} onChange={e => setMediaBackup(e.target.value)}/></label><label>Atlas Program Backup identity<input value={programBackup} onChange={e => setProgramBackup(e.target.value)}/></label><label>WordPress backup reference<input value={wpBackup} onChange={e => setWpBackup(e.target.value)}/></label><label>WordPress backup timestamp<input type="datetime-local" value={wpBackupTime} onChange={e => setWpBackupTime(e.target.value)}/></label><label><input type="checkbox" checked={databaseIncluded} onChange={e => setDatabaseIncluded(e.target.checked)}/> Database included</label><label><input type="checkbox" checked={pluginsIncluded} onChange={e => setPluginsIncluded(e.target.checked)}/> Plugin files included</label><label><input type="checkbox" checked={restoreConfirmed} onChange={e => setRestoreConfirmed(e.target.checked)}/> Restore capability confirmed</label><div className="buttonRow"><button className="primaryButton buttonWithIcon" disabled={busy || !backupsReady} onClick={runDry}><RefreshCw size={16}/>Run metadata dry run</button><button className="secondaryButton buttonWithIcon" disabled={busy} onClick={runVerify}><RefreshCw size={16}/>Verify rendered metadata</button></div>{verify && <><p><strong>{verify.metadata_correct ? "Metadata verified; no apply needed." : "Metadata is not in the verified final state."}</strong></p><GateList gates={verify.gate_results}/></>}</section>
    {error && <div className="errorBanner"><AlertTriangle size={18}/>{error}</div>}
    {dry && <><section className="panel"><h2><FileCode2 size={20}/>Exact payload</h2><dl className="detailGrid"><div><dt>Plugin</dt><dd>{dry.plugin_version}</dd></div><div><dt>Payload SHA-256</dt><dd><code>{dry.payload_hash}</code></dd></div><div><dt>Meta description</dt><dd>{dry.payload.meta_description}</dd></div><div><dt>Canonical social image</dt><dd>{dry.payload.open_graph["og:image"]}</dd></div><div><dt>Excluded media</dt><dd>{dry.payload.excluded_media_ids.join(", ")}</dd></div></dl><GateList gates={dry.gate_results}/></section>
    <section className="panel wordpressApplyPanel"><h2>Guarded Orlando metadata apply</h2><label>Confirmed Atlas Data Backup JSON<input value={dataBackup} onChange={e => setDataBackup(e.target.value)} placeholder="atlas-backup-....json"/></label><label>Atlas Media Backup identity<input value={mediaBackup} onChange={e => setMediaBackup(e.target.value)}/></label><label>Atlas Program Backup identity<input value={programBackup} onChange={e => setProgramBackup(e.target.value)}/></label><label>WordPress backup identifier<input value={wpBackup} onChange={e => setWpBackup(e.target.value)}/></label><label>WordPress backup timestamp<input type="datetime-local" value={wpBackupTime} onChange={e => setWpBackupTime(e.target.value)}/></label><label><input type="checkbox" checked={databaseIncluded} onChange={e => setDatabaseIncluded(e.target.checked)}/> WordPress database included</label><label><input type="checkbox" checked={pluginsIncluded} onChange={e => setPluginsIncluded(e.target.checked)}/> Plugin files included</label><label><input type="checkbox" checked={restoreConfirmed} onChange={e => setRestoreConfirmed(e.target.checked)}/> Restore capability confirmed</label><label>Exact phrase: <code>{dry.confirmation_phrase ?? "Available only after all gates pass"}</code><input value={phrase} onChange={e => setPhrase(e.target.value)}/></label><button className="dangerButton" disabled={!canApply || busy} onClick={apply}>Apply Orlando metadata</button><p className="helperText">The backend reruns all gates and verifies the returned and rendered payload hashes. Cache purge is never called.</p></section></>}
    {result && <section className="panel"><h2>Metadata apply verified</h2><p>Revision {result.wordpress_revision}; audit {result.audit_id}; payload <code>{result.payload_hash}</code>.</p></section>}
    <section className="panel wordpressApplyPanel"><h2>Separate guarded rollback</h2><button className="secondaryButton" disabled={busy} onClick={runRollbackDry}>Run rollback dry run</button>{rollback && <><GateList gates={rollback.gate_results}/><label>Exact rollback phrase: <code>{rollback.confirmation_phrase ?? "Unavailable"}</code><input value={rollbackPhrase} onChange={e => setRollbackPhrase(e.target.value)}/></label><button className="dangerButton" disabled={!rollbackReady || busy} onClick={applyRollback}>Roll back Orlando metadata</button></>}</section>
  </section>;
}

function GateList({ gates }: { gates: WordPressMetadataGate[] }) { return <div className="wordpressGateList">{gates.map(g => <div key={g.code} className={g.passed ? "gateItem passed" : "gateItem blocked"}>{g.passed ? <CheckCircle2 size={17}/> : <AlertTriangle size={17}/>}<div><strong>{g.label}</strong><span>{g.message}</span></div></div>)}</div>; }
