import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, LockKeyhole } from "lucide-react";
import { apiRequest } from "../api";
import type { WordPressDeploymentAuthorization, WordPressDeploymentDryRun, WordPressDeploymentGate, WordPressDeploymentReadiness, WordPressDeploymentVerification } from "../types";

const PAGE_ID = 41;

export default function WordPressMetadataBridgeInstallPage() {
  const [proof, setProof] = useState({ atlas_data_backup_file:"", atlas_media_backup_file:"", atlas_program_backup_file:"", wordpress_backup_method:"SiteGround on-demand full-site backup", wordpress_backup_reference:"", wordpress_backup_completed_at:"", wordpress_database_included_attestation:false, wordpress_plugins_included_attestation:false, wordpress_restore_capability_attestation:false, confirmer_identity:"Shawn Manchette", php_error_log_findings:"No findings", observed_write_summary:"No WordPress write performed by Atlas" });
  const [operator,setOperator]=useState("Shawn Manchette"), [phrase,setPhrase]=useState(""), [evidenceDirectory,setEvidenceDirectory]=useState("");
  const [dry,setDry]=useState<WordPressDeploymentDryRun|null>(null), [authorization,setAuthorization]=useState<WordPressDeploymentAuthorization|null>(null), [verification,setVerification]=useState<WordPressDeploymentVerification|null>(null);
  const [reported,setReported]=useState(false), [manualDone,setManualDone]=useState(false);
  const [busy,setBusy]=useState(false), [error,setError]=useState<string|null>(null);
  const [readiness,setReadiness]=useState<WordPressDeploymentReadiness|null>(null);
  useEffect(()=>{void apiRequest<WordPressDeploymentReadiness>("/api/wordpress/deployment/metadata-bridge/install/readiness").then(setReadiness).catch(value=>setError(value instanceof Error?value.message:"Release readiness failed."))},[]);
  const update=(key:string,value:string|boolean)=>setProof(current=>({...current,[key]:value}));
  const payload=()=>({...proof,wordpress_backup_completed_at:new Date(proof.wordpress_backup_completed_at).toISOString()});
  async function run<T>(work:()=>Promise<T>,save:(value:T)=>void){setBusy(true);setError(null);try{save(await work())}catch(value){setError(value instanceof Error?value.message:"Request failed.")}finally{setBusy(false)}}
  function preflight(){setAuthorization(null);setReported(false);setVerification(null);void run(()=>apiRequest<WordPressDeploymentDryRun>(`/api/wordpress/deployment/metadata-bridge/install/dry-run/${PAGE_ID}`,{method:"POST",body:JSON.stringify(payload())}),setDry)}
  function authorize(){if(!dry?.confirmation_token)return;void run(()=>apiRequest<WordPressDeploymentAuthorization>(`/api/wordpress/deployment/metadata-bridge/install/authorize/${PAGE_ID}`,{method:"POST",body:JSON.stringify({...payload(),confirmation_token:dry.confirmation_token,confirmation_phrase:phrase,operator,shawn_approved_at:new Date().toISOString(),evidence_directory:evidenceDirectory})}),setAuthorization)}
  function report(){if(!authorization)return;void run(()=>apiRequest(`/api/wordpress/deployment/metadata-bridge/install/report-manual-complete/${PAGE_ID}`,{method:"POST",body:JSON.stringify({audit_id:authorization.audit_id,operator,manual_upload_completed_attestation:manualDone})}),()=>setReported(true))}
  function verify(){if(!authorization)return;void run(()=>apiRequest<WordPressDeploymentVerification>(`/api/wordpress/deployment/metadata-bridge/install/verify/${PAGE_ID}`,{method:"POST",body:JSON.stringify({audit_id:authorization.audit_id,operator,php_error_log_findings:proof.php_error_log_findings})}),setVerification)}
  return <section className="page wordpressPublishSafetySandboxPage"><header className="pageHeader"><div><span className="eyebrow">{readiness?.release?.atlas_version ?? readiness?.source_expectations.deployment_workflow_version ?? "Release identity loading"} · Orlando page 41 · WordPress post 8</span><h1>Guarded Manual Bridge Installation</h1><p>Atlas verifies and records. Shawn performs the supported WordPress Admin upload. Atlas never uploads or activates the plugin.</p></div></header>
    <div className="wordpressSafetyNotice"><LockKeyhole size={22}/><div><strong>Installation-only hard stop</strong><p>No password, cookie, nonce, upload, activation, metadata apply, cache purge, removal, restore, media, or bulk controls exist here.</p></div></div>
    {error&&<div className="errorBanner"><AlertTriangle size={18}/>{error}</div>}
    <section className="panel"><h2>1. Backup and artifact preflight</h2><div className="wordpressSettingsGrid">
      <Field label="Atlas Data Backup JSON" value={proof.atlas_data_backup_file} onChange={v=>update("atlas_data_backup_file",v)}/><Field label="Atlas Media Backup identity" value={proof.atlas_media_backup_file} onChange={v=>update("atlas_media_backup_file",v)}/><Field label="Atlas Program Backup identity" value={proof.atlas_program_backup_file} onChange={v=>update("atlas_program_backup_file",v)}/><Field label="WordPress backup method" value={proof.wordpress_backup_method} onChange={v=>update("wordpress_backup_method",v)}/><Field label="Durable WordPress backup reference" value={proof.wordpress_backup_reference} onChange={v=>update("wordpress_backup_reference",v)}/><label>Backup completion with timezone<input type="datetime-local" value={proof.wordpress_backup_completed_at} onChange={e=>update("wordpress_backup_completed_at",e.target.value)}/></label><Field label="Confirmer identity" value={proof.confirmer_identity} onChange={v=>update("confirmer_identity",v)}/></div>
      {readiness&&<p><strong>{readiness.release?.atlas_version ?? "Release identity unavailable"}</strong> · plugin {readiness.source_expectations.plugin_version} · <code>{readiness.source_expectations.plugin_zip_filename}</code>{readiness.release_error&&<><br/><span className="helperText">{readiness.release_error}</span></>}</p>}<Checks values={proof} update={update}/><button className="primaryButton" disabled={busy||!proof.wordpress_backup_completed_at||readiness?.release_status!=="verified"} onClick={preflight}>Run read-only preflight</button>{dry&&<><p><strong>{dry.ready?"Preflight ready":"Preflight blocked"}</strong> · ZIP <code>{dry.artifact.zip_file_name}</code> · SHA-256 <code>{dry.artifact.zip_sha256}</code></p><Gates gates={dry.gate_results}/></>}</section>
    {dry?.ready&&<section className="panel"><h2>2. Authorize manual installation</h2><Field label="Operator" value={operator} onChange={setOperator}/><Field label="Evidence directory (approved structure)" value={evidenceDirectory} onChange={setEvidenceDirectory}/><label>Exact phrase: <code>{dry.confirmation_phrase}</code><input value={phrase} onChange={e=>setPhrase(e.target.value)}/></label><button className="dangerButton" disabled={busy||phrase!==dry.confirmation_phrase||!evidenceDirectory} onClick={authorize}>Authorize Manual Installation</button></section>}
    {authorization&&<section className="panel"><h2>3. Manual WordPress Admin instructions</h2><p>Audit states: <code>{authorization.state_history.join(" → ")}</code></p><div className="errorBanner"><AlertTriangle size={18}/><strong>{authorization.warning}</strong></div><p><strong>{authorization.zip_file_name}</strong><br/><code>{authorization.zip_sha256}</code></p><ol>{authorization.instructions.map(item=><li key={item}>{item}</li>)}</ol><label><input type="checkbox" checked={manualDone} onChange={e=>setManualDone(e.target.checked)}/> I completed the manual upload and did not activate the plugin.</label><button className="primaryButton" disabled={busy||!manualDone} onClick={report}>I completed the manual upload</button></section>}
    {reported&&<section className="panel"><h2>4. Read-only verification</h2><p>Safety conclusions come from read-only inventory, page, render, media, and cache snapshots—not operator pass/fail checkboxes.</p><label>PHP/error-log findings<textarea value={proof.php_error_log_findings} onChange={e=>update("php_error_log_findings",e.target.value)}/></label><button className="primaryButton" disabled={busy} onClick={verify}>Verify Installation (read-only)</button>{verification&&<><h3>{verification.verified?"Verified — hard stop":"Verification failed — hard stop"}</h3><p>Audit states: <code>{verification.state_history.join(" → ")}</code></p><Gates gates={verification.gate_results}/>{verification.inspection_limitations.map(item=><p className="helperText" key={item}>{item}</p>)}<p>No activation or later-version action is available.</p></>}</section>}
  </section>;
}

function Field({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label>{label}<input value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Checks({values,update}:{values:Record<string,string|boolean>;update:(key:string,value:boolean)=>void}){return <div><label><input type="checkbox" checked={Boolean(values.wordpress_database_included_attestation)} onChange={e=>update("wordpress_database_included_attestation",e.target.checked)}/> WordPress database included</label><label><input type="checkbox" checked={Boolean(values.wordpress_plugins_included_attestation)} onChange={e=>update("wordpress_plugins_included_attestation",e.target.checked)}/> wp-content/plugins included</label><label><input type="checkbox" checked={Boolean(values.wordpress_restore_capability_attestation)} onChange={e=>update("wordpress_restore_capability_attestation",e.target.checked)}/> Restore capability confirmed</label></div>}
function Gates({gates}:{gates:WordPressDeploymentGate[]}){return <div className="wordpressGateList">{gates.map(g=><div key={g.code} className={g.passed?"gateItem passed":"gateItem blocked"}>{g.passed?<CheckCircle2 size={17}/>:<AlertTriangle size={17}/>}<div><strong>{g.label}</strong><span>{g.message}</span></div></div>)}</div>}
