"""Provider-neutral Website Builder contracts.

This package is deliberately pure: persistence, FastAPI, AtlasOps360, and
provider SDKs belong outside this dependency boundary.
"""

from app.website_builder_core.contracts import (
    ATLAS_OWNED_FORM_MODES,
    DEFAULT_CUSTOMER_ENTRY_FIELD_COUNT,
    FORM_DELIVERY_MODES,
    MAXIMUM_CUSTOMER_ENTRY_FIELD_COUNT,
    RESERVED_OPTIONAL_FIELD_KEYS,
    STANDARD_CUSTOMER_ENTRY_FIELD_KEYS,
    STANDARD_CUSTOMER_ENTRY_FIELD_LABELS,
    SYSTEM_FORM_CONTROL_KEYS,
    DeliveryAdapterContext,
    DeliveryAttemptResult,
    DeliveryRecipientSnapshot,
    FormDeliveryMode,
    FormDeliveryPresentation,
    FormRequestSecurityPolicy,
    NormalizedFormDefinition,
    NormalizedFormFieldDefinition,
    NormalizedOptionalFieldValue,
    NormalizedSubmissionEnvelope,
    OptionalFormFieldChoice,
    OptionalFormFieldDefinition,
    OptionalFormFieldValidationContract,
    ProviderDeliveryContext,
    UNIVERSAL_ESTIMATE_FORM_DEFINITION,
    UNIVERSAL_FORM_REQUEST_SECURITY,
    normalize_form_field_key,
    normalize_optional_field_value,
    optional_form_field_definition_payload,
    validate_submission_optional_field_binding,
)
from app.website_builder_core.readiness import (
    FormDeliveryReadiness,
    FormDeliveryReadinessBlocker,
    FormDeliveryReadinessInput,
    evaluate_form_delivery_readiness,
)
from app.website_builder_core.registry import (
    ProviderDescriptor,
    ProviderRegistration,
    ProviderRegistry,
)

__all__ = [
    "ATLAS_OWNED_FORM_MODES",
    "DEFAULT_CUSTOMER_ENTRY_FIELD_COUNT",
    "FORM_DELIVERY_MODES",
    "MAXIMUM_CUSTOMER_ENTRY_FIELD_COUNT",
    "RESERVED_OPTIONAL_FIELD_KEYS",
    "STANDARD_CUSTOMER_ENTRY_FIELD_KEYS",
    "STANDARD_CUSTOMER_ENTRY_FIELD_LABELS",
    "SYSTEM_FORM_CONTROL_KEYS",
    "DeliveryAdapterContext",
    "DeliveryAttemptResult",
    "DeliveryRecipientSnapshot",
    "FormDeliveryMode",
    "FormDeliveryPresentation",
    "FormDeliveryReadiness",
    "FormDeliveryReadinessBlocker",
    "FormDeliveryReadinessInput",
    "FormRequestSecurityPolicy",
    "NormalizedFormDefinition",
    "NormalizedFormFieldDefinition",
    "NormalizedOptionalFieldValue",
    "NormalizedSubmissionEnvelope",
    "OptionalFormFieldChoice",
    "OptionalFormFieldDefinition",
    "OptionalFormFieldValidationContract",
    "ProviderDeliveryContext",
    "ProviderDescriptor",
    "ProviderRegistration",
    "ProviderRegistry",
    "UNIVERSAL_ESTIMATE_FORM_DEFINITION",
    "UNIVERSAL_FORM_REQUEST_SECURITY",
    "evaluate_form_delivery_readiness",
    "normalize_form_field_key",
    "normalize_optional_field_value",
    "optional_form_field_definition_payload",
    "validate_submission_optional_field_binding",
]
